"""Default RAG pipeline tuning knobs."""

RETRIEVAL_TOP_K = 30
RERANK_TOP_N = 5
MULTI_QUERY_COUNT = 3
RRF_K = 60
DEFAULT_TOP_CHUNKS = 5
MIN_TOP_CHUNKS = 3
MAX_TOP_CHUNKS = 21
DECISION_TREE_MIN_SIMILARITY = 0.30
DECISION_TREE_MAX_APPLICABLE = 1
DECISION_TREE_NO_MATCH_TOKEN = "NO_DECISION_TREE_MATCH"
